@startuml
split
   -[hidden]->
    start
   :A;
split again
   -[hidden]->
   :B;
split again
   -[hidden]->
   :C;
end split
:D;
@enduml

@startmindmap
* Course
** SubCourse_1
*** [ Teacher ]
*** [ Sub Teachers ] = []
** .\n.\n.
** SubCourse_n
*** [ Teacher ]
*** [ Sub Teachers ] = []
@endmindmap



@startuml
start
:submit Salary request;
:get the Course();
:ceate a salary policy;
:Course_policy
course_level = Course.course_level
Base_salary = Course.capacity[Course.course_type] .
Cancellation_factor = course_Cancellation_factor;

note
Teacher Salary
end note
:Get All Course subCourse;
repeat :while subcourse in Course (not deleted);
    :Get All subCourse sessions;
    repeat :while session in subcourse (not deleted);

if (
session.canceled
or
not session.session_Report
) then (True)
            :session.teacher -> canceled += 1;
        (False     )elseif (
session.is_sub
        ) then (True)
            :subcourse.teacher -> session_point -= 1
            session.teacher -- -> session_point += 2;
        else
            :session.teacher -> attended session += 1;
        endif
    repeat while (Session exist in Sub Course) is (yes)
    ->no;
repeat while (Sub Course exist in Course) is (yes)
->no;
stop

@enduml
