@startuml

start
note
Teacher Salary
end note
:Get All Course subCourse;
repeat :while subcourse in Course (not deleted);
    :Get All subCourse sessions;
    repeat :while session in subcourse (not deleted);
if (
session.canceled
or
not session.session_Report
) then (True)
            :session.teacher -> canceled += 1;
        (False     )elseif (
session.is_sub
        ) then (True)
            :subcourse.teacher -> session_point -= 1
            session.teacher -- -> session_point += 2;
        else
            :session.teacher -> attended session += 1;
        endif
    repeat while (Session exist in Sub Course) is (yes)
    ->no;
repeat while (Sub Course exist in Course) is (yes)
->no;
stop

@enduml
