from .Base import *
from .Configs import *
from .Course import *
from .Entity import *
from .NoCategory import *
from .Salary import *
from .Survey import *
from .TagsCategories import *
from .User_form import *
from .Template import *
