from .Base import *
from .Course import *
from .Employee_forms import *
from .Entity import *
from .NoCategory import *
from .Salary import *
from .Survey import *
from .TagsCategories import *
from .User import *
from .teacher_forms import *
from .Configs import *