version: '3.1'

services:
  db:
    image: postgres
    # restart: always
    volumes:
      - postgres_Volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tmp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
    ports:    
      - 5432:5432

  adminer:
     image: adminer
     # restart: always
     ports:
       - 8080:8080

volumes:
  postgres_Volume:
    external: true