version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: null
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s [%(levelname)s] %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    formatter: default
    class: logging.FileHandler
    filename: log/uvicorn.log
    mode: a
  access:
    formatter: access
    class: logging.FileHandler
    filename: log/access.log
    mode: a
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: False
